- hosts: localhost

  tasks:

    - name: Replace Docker image
      replace:
        path: ../k8s/deployment.yaml
        regexp: 'IMAGE_PLACEHOLDER'
        replace: '{{ image }}'

    - name: Apply Deployment
      command: kubectl apply -f ../k8s/deployment.yaml --validate=false

    - name: Apply Service
      command: kubectl apply -f ../k8s/service.yaml --validate=false

    - name: Apply Ingress
      command: kubectl apply -f ../k8s/ingress.yaml --validate=false